INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '80001',  '50.1173825',  '1.8323901',  'ABBEVILLE',  '80100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '80002',  '49.8381',  '2.8209616',  'ABLAINCOURT-PRESSOIR',  '80320', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '78003',  '48.5168526',  '1.8351104',  'ABLIS',  '78660', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '13001',  '43.484959',  '5.41954',  'AIX-EN-PROVENCE',  '13080', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '81004',  '43.9329634',  '2.1548473',  'ALBI',  '81000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '61001',  '48.430625',  '0.083175',  'ALENCON',  '61000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '80021',  '49.924529',  '2.2831512',  'AMIENS',  '80080', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49007',  '47.497501',  '-0.55314',  'ANGERS',  '49000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '74010',  '45.8971718',  '6.1251614',  'ANNECY',  '74000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '74012',  '46.194181',  '6.2389698',  'ANNEMASSE',  '74100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '36006',  '46.58889',  '1.51911',  'ARGENTON-SUR-CREUSE',  '36200', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '62041',  '50.283829',  '2.74686',  'ARRAS',  '62000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '89024',  '47.79605',  '3.569305',  'AUXERRE',  '89000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '84007',  '43.9470042',  '4.8209596',  'AVIGNON',  '84000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '50025',  '48.686375',  '-1.361919',  'AVRANCHES',  '50300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '64102',  '43.5031621',  '-1.4724751',  'BAYONNE',  '64100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '21054',  '47.0239813',  '4.8382698',  'BEAUNE',  '21200', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '90010',  '47.6455',  '6.84104',  'BELFORT',  '90000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '25056',  '47.2711117',  '6.0282445',  'BESANCON',  '25000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '27065',  '49.345496',  '0.341904',  'BEUZEVILLE',  '27210', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '34032',  '43.3416692',  '3.238251',  'BEZIERS',  '34500', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '33063',  '44.8445542',  '-0.5494198',  'BORDEAUX',  '33100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '62160',  '50.72858',  '1.60836',  'BOULOGNE-SUR-MER',  '62200', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '1053',  '46.203289',  '5.22139',  'BOURG-EN-BRESSE',  '1000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '18033',  '47.0818269',  '2.4039338',  'BOURGES',  '18000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '38053',  '45.589125',  '5.28195',  'BOURGOIN-JALLIEU',  '38300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '27107',  '49.39446',  '0.62239',  'BOURNEVILLE',  '27500', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '19031',  '45.1487308',  '1.5195771',  'BRIVE-LA-GAILLARDE',  '19100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '14118',  '49.18462',  '-0.3719',  'CAEN',  '14000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '46042',  '44.4467',  '1.440755',  'CAHORS',  '46000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '62193',  '50.95274',  '1.86869',  'CALAIS',  '62100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59122',  '50.1753508',  '3.2343689',  'CAMBRAI',  '59400', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '83031',  '43.3922796',  '6.3425245',  'CANNET-DES-MAURES',  '83340', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '51108',  '48.9687925',  '4.3706849',  'CHALONS-EN-CHAMPAGNE',  '51000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '71076',  '46.7842185',  '4.8529482',  'CHALON-SUR-SAONE',  '71100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '73065',  '45.5667045',  '5.9209874',  'CHAMBERY',  '73000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '8105',  '49.768902',  '4.71241',  'CHARLEVILLE-MEZIERES',  '8000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '28085',  '48.446751',  '1.50341',  'CHARTRES',  '28000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '36044',  '46.8027',  '1.69028',  'CHATEAUROUX',  '36000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49092',  '47.212545',  '-0.730529',  'CHEMILLE',  '49120', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49099',  '47.062592',  '-0.880687',  'CHOLET',  '49300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '63113',  '45.780788',  '3.11949',  'CLERMONT-FERRAND',  '63000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '80204',  '50.0092165',  '2.8632552',  'COMBLES',  '80360', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49110',  '47.559007',  '-0.391733',  'CORZE',  '49140', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '45115',  '48.040725',  '3.058595',  'COURTENAY',  '45320', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '21231',  '47.3237985',  '5.0386146',  'DIJON',  '21000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '39198',  '47.0892522',  '5.4878408',  'DOLE',  '39100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59178',  '50.37986',  '3.09926',  'DOUAI',  '59500', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59183',  '51.044331',  '2.41579',  'DUNKERQUE',  '59240', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49127',  '47.67084',  '-0.243534',  'DURTAL',  '49430', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '85084',  '46.7718837',  '-1.2266629',  'ESSARTS',  '85140', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '85092',  '46.4659524',  '-0.8060646',  'FONTENAY-LE-COMTE',  '85200', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '35115',  '48.3477251',  '-1.1957642',  'FOUGERES',  '35300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '38185',  '45.197071',  '5.71048',  'GRENOBLE',  '38000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '76351',  '49.476996',  '0.1639479',  'HAVRE',  '76600', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '76369',  '49.6327354',  '1.0833797',  'HOUSSAYE-BERANGER',  '76690', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '53130',  '48.0678944',  '-0.7646412',  'LAVAL',  '53000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '62498',  '50.43639',  '2.81861',  'LENS',  '62300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59350',  '50.629059',  '3.06038',  'LILLE',  '59000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '87085',  '45.85368',  '1.22519',  'LIMOGES',  '87100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '69123',  '45.7712918',  '4.8280831',  'LYON',  '69001', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '71270',  '46.30415',  '4.833486',  'MACON',  '71000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '72181',  '48.0157803',  '0.1609266',  'MANS',  '72000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '13055',  '43.294418',  '5.35999',  'MARSEILLE',  '13001', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '57463',  '49.102329',  '6.18289',  'METZ',  '57000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '73157',  '45.2016389',  '6.6729027',  'MODANE',  '73500', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '45208',  '47.998435',  '2.733055',  'MONTARGIS',  '45200', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '82121',  '44.0310432',  '1.3469247',  'MONTAUBAN',  '82000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '34172',  '43.6047275',  '3.9011747',  'MONTPELLIER',  '34000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '68224',  '47.7413496',  '7.3456857',  'MULHOUSE',  '68100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '54395',  '48.6896459',  '6.1737197',  'NANCY',  '54000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '44109',  '47.22205',  '-1.55062',  'NANTES',  '44000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '11262',  '43.14959',  '3.03367',  'NARBONNE',  '11100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '77333',  '48.2673099',  '2.6953904',  'NEMOURS',  '77140', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '76462',  '49.7332381',  '1.4431376',  'NEUFCHATEL-EN-BRAY',  '76270', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '58194',  '46.9871775',  '3.1616028',  'NEVERS',  '58000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '6088',  '43.714211',  '7.2469',  'NICE',  '6000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '30189',  '43.86256',  '4.36035',  'NIMES',  '30000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '79191',  '46.3238567',  '-0.4575836',  'NIORT',  '79000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59449',  '50.473943',  '3.241846',  'ORCHIES',  '59310', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '45234',  '47.914139',  '1.90991',  'ORLEANS',  '45000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '75101',  '48.8640493',  '2.3310526',  'PARIS',  '75001', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '64445',  '43.320332',  '-0.34378',  'PAU',  '64000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '66136',  '42.7201813',  '2.8876436',  'PERPIGNAN',  '66000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '86194',  '46.5831743',  '0.3464227',  'POITIERS',  '86000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '1304',  '46.05162',  '5.33534',  'PONT-D\'AIN',  '1160', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '51454',  '49.2442751',  '4.0346212',  'REIMS',  '51100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '35238',  '48.112049',  '-1.686',  'RENNES',  '35000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '17299',  '45.9450336',  '-0.9756731',  'ROCHEFORT',  '17300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '85191',  '46.6693784',  '-1.418721',  'ROCHE-SUR-YON',  '85000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '52432',  '47.9508769',  '5.2875705',  'ROLAMPONT',  '52260', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '76540',  '49.4464909',  '1.0976001',  'ROUEN',  '76000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '17415',  '45.747437',  '-0.6371092',  'SAINTES',  '17100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '42218',  '45.45089',  '4.38889',  'SAINT-ETIENNE',  '42000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '74236',  '45.9473788',  '6.677223',  'SAINT-GERVAIS-LES-BAINS',  '74190', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '74243',  '46.1437955',  '6.0804914',  'SAINT-JULIEN-EN-GENEVOIS',  '74160', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '73270',  '45.5694448',  '6.1543571',  'SAINT-PIERRE-D\'ALBIGNY',  '73250', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '2691',  '49.862839',  '3.29748',  'SAINT-QUENTIN',  '2100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '76462',  '49.6729343',  '1.2827692',  'SAINT-SAENS',  '76680', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '13103',  '43.643681',  '5.04872',  'SALON-DE-PROVENCE',  '13300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '49328',  '47.259765',  '-0.079319',  'SAUMUR',  '49400', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '89387',  '48.19887',  '3.28268',  'SENS',  '89100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '67482',  '48.6019858',  '7.7835217',  'STRASBOURG',  '67000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '65440',  '43.2376195',  '0.0700051',  'TARBES',  '65000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '83137',  '43.1200697',  '5.9383291',  'TOULON',  '83000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '31555',  '43.6043902',  '1.448302',  'TOULOUSE',  '31000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '37261',  '47.387821',  '0.69951',  'TOURS',  '37000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '10387',  '48.292339',  '4.07554',  'TROYES',  '10000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '26362',  '44.923519',  '4.91814',  'VALENCE',  '26000', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59606',  '50.337799',  '3.52091',  'VALENCIENNES',  '59300', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '18279',  '47.2230013',  '2.0659806',  'VIERZON',  '18100', NULL);
INSERT INTO  `COVAMI`.`City`(`id` ,`insee` ,`latitude` ,`longitude` ,`name` ,`postalCode` ,`country_id`) VALUES (NULL ,  '59009',  '50.66214',  '3.145935',  'VILLENEUVE-D\'ASCQ',  '59491', NULL);


INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '2' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '43' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '12' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '48' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '12' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '93' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '79' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '85' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '107' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '81' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '3' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '82' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '8' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '44' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '50' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '63' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '38' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '3' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '29', '20' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '29', '27' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '29', '92' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '29', '82' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '55', '27' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '92', '56' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '7' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '1' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '23' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '31' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '49' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '67' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '45' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '102' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '43', '32' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '43', '110' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '39' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '11' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '60' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '28' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '30' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '111', '68' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '58', '48' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '58', '110' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '112', '80' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '112', '110' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '49', '59' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '31', '12' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '31', '32' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '31', '98' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '31', '34' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '31', '108' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '1', '75' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '1', '92' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '1', '6' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '1', '63' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '1', '107' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '20', '55' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '20', '75' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '20', '7' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '20', '2' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '20', '98' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '65', '71' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '65', '91' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '65', '46' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '65', '17' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '87', '37' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '70', '103' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '70', '18' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '70', '19' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '70', '47' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '70', '17' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '46', '47' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '46', '24' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '87' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '34' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '65' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '103' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '62', '24' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '62', '86' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '62', '96' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '62', '10' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '62', '95' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '96', '9' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '96', '36' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '96', '54' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '86', '61' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '26' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '36' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '97' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '66' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '94' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '26', '54' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '54', '109' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '102' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '108' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '91' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '64', '105' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '54', '4' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '54', '64' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '78', '100' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '33', '105' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '74' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '45' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '13' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '46' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '17' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '35' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '62' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '82', '61' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '106', '73' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '68' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '106' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '16' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '16', '104' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '16', '106' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '83' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '106', '5' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '109' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '14' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '100' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '61', '64' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '111' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '25' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '81', '42' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '42', '94' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '42', '21' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '74', '67' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '74', '76' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '77', '33' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '77', '4' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '57', '63' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '51' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '52' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '72', '79' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '93', '89' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '88', '53' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '88', '15' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '88', '29' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '44', '101' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '44', '107' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '44', '111' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '90', '51' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '90', '41' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '90', '40' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '90', '8' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '6', '29' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '28' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '22', '42' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '84', '73' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '84', '21' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '84', '69' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '84', '78' );
INSERT INTO `COVAMI`.`City_City` ( `City_id` , `neighborhood_id` ) VALUES ( '84', '14' );